apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: securitydb
    user: postgres
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 150
    secureJsonData:
      password: postgres_secure_password_2024

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
